In [ ]:
## 2025년 8월 24일 화이팅입니다!!!

'''
오늘 들을 강의는 AICE에서 다룰 데이터 분석을 위해 
pandas와 numpy 라이브러리의 기본 문법을
간략하게 알아보는 강의이다.
'''

In [2]:
## 라이브러리 설치
import pandas as pd
import numpy as np

# Numpy 기본 문법!!

In [13]:
# 1차원 배열 생성
arr1 = np.array([1,2,3,4,5])
print(arr1)
type(arr1)

[1 2 3 4 5]


numpy.ndarray

In [18]:
# 2차원 배열(행렬)
mtx = np.array([[1,2,3], [4,5,6]])   # 리스트 내에 리스트를 인자로 가짐
print(mtx)
type(mtx)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

# 엑셀에서 1열과 2열의 연산을 시킨 것과 동일한 결과를 얻음.

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


> np.array() 함수는 n차원 배열을 만들어주는 함수이다.

>기본적인 파이썬 리스트는 연산에 부적합하여 사용한다.

# Pandas 기본 문법!!

In [ ]:
# Series 생성 - 엑셀과 같은 데이터프레임을 생성해줌!
data = [10, 20, 30, 40]
series = pd.Series(data)
print("Series:\n", series, sep = '')

Series:
0    10
1    20
2    30
3    40
dtype: int64


In [24]:
df = pd.DataFrame({'이름' : ['철수','영희','민수'],
                  '나이' : [20,21,19],
                  '성적' : [85,90,88]})
print(df)

   이름  나이  성적
0  철수  20  85
1  영희  21  90
2  민수  19  88
